language : python

python:
  - "3.6"  

before_script:
  - pip install -r requirements.txt

script:
  # # - python -m pytest tests/
  # - nosetests --with-coverage --cover-package=StoreManager
  - pytest --cov=StoreManager tests/
after_success:
  - coveralls

  