language : python

python:
  - "3.6"  

before_script:
  - pip install -r requirements.txt

script:
  - python3 -m pytest --cov StoreManager --cov-report term-missing
  
after_success:
  - coveralls

  